# Generated by Django 4.2.4 on 2023-08-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('fb_url', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReviewButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=255)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(max_length=255)),
                ('p', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(max_length=255)),
                ('p', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_alt', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_section_bg_image', models.URLField()),
                ('other_projects_header_h2', models.CharField(max_length=255)),
                ('parallax_bg_image', models.URLField()),
                ('parallax_logo_url', models.URLField()),
                ('how_we_work_header_h1', models.CharField(max_length=255)),
                ('about_us_image_url', models.URLField()),
                ('about_us_image_alt', models.CharField(blank=True, max_length=255)),
                ('about_us_h3', models.CharField(max_length=255)),
                ('about_us_p', models.TextField()),
                ('about_us_button_text', models.CharField(max_length=255)),
                ('customer_reviews_bg_image', models.URLField()),
                ('customer_reviews_h1', models.CharField(max_length=255)),
                ('customer_reviews_p', models.TextField()),
                ('customer_reviews_logo_url', models.URLField()),
                ('our_knowledge_header_h1', models.CharField(max_length=255)),
                ('our_knowledge_header_p', models.TextField()),
                ('best_furniture_parallax_bg_image', models.URLField()),
                ('best_furniture_parallax_h1', models.CharField(max_length=255)),
                ('footer_header_h1', models.CharField(max_length=255)),
                ('footer_header_p', models.TextField()),
                ('best_furniture_parallax_button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_furniture_button', to='admin_panel.button')),
                ('contact_icons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.contacticon')),
                ('customer_reviews_buttons', models.ManyToManyField(to='admin_panel.customerreviewbuttons')),
                ('folders', models.ManyToManyField(to='admin_panel.folders')),
                ('footer_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.footercontact')),
                ('gallery', models.ManyToManyField(to='admin_panel.gallery')),
                ('how_we_work_button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='how_we_work_button', to='admin_panel.button')),
                ('main_header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.mainheader')),
                ('our_knowledge_button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='our_knowledge_button', to='admin_panel.button')),
                ('parallax_button', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parallax_button', to='admin_panel.button')),
                ('slider_items', models.ManyToManyField(to='admin_panel.slideritem')),
            ],
        ),
    ]
