# Generated by Django 4.2.4 on 2023-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_section', models.JSONField()),
                ('other_projects', models.JSONField()),
                ('parallax', models.JSONField()),
                ('how_we_work', models.JSONField()),
                ('about_us', models.JSONField()),
                ('customer_reviews', models.JSONField()),
                ('our_knowledge', models.JSONField()),
                ('best_furniture_parallax', models.JSONField()),
                ('footer', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='best_furniture_parallax_button',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='contact_icons',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='customer_reviews_buttons',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='footer_contact',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='how_we_work_button',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='main_header',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='our_knowledge_button',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='parallax_button',
        ),
        migrations.RemoveField(
            model_name='websitedata',
            name='slider_items',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='ContactIcon',
        ),
        migrations.DeleteModel(
            name='CustomerReviewButtons',
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
        migrations.DeleteModel(
            name='FooterContact',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='MainHeader',
        ),
        migrations.DeleteModel(
            name='SliderItem',
        ),
        migrations.DeleteModel(
            name='WebsiteData',
        ),
    ]
